<a href="https://colab.research.google.com/github/rijul27/Exploring-Pandas/blob/main/PandasMethods1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv')

In [ ]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
df.drop('species',axis=1)

,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...
339,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
# for permanently delete, by default inplace is false
df.drop('species',axis=1, inplace = True)

In [ ]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
# delete row, for permanently delete use inplace

df.drop(4)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
#  set one or more columns as the DataFrame's index. In this specific case,
# it's taking the island column from your DataFrame df and making it the new
# index of the DataFrame. and for permanently modification use inplace

# To prevent KeyError if 'island' is already the index (and thus not a column),
# we first reset the index to make 'island' a column again, if it's not already a column.
if 'island' not in df.columns:
    df.reset_index(inplace=True)
df.set_index('island', inplace=True)

In [ ]:
df

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
island,,,,,,
Torgersen,Adelie,39.1,18.7,181.0,3750.0,MALE
Torgersen,Adelie,39.5,17.4,186.0,3800.0,FEMALE
Torgersen,Adelie,40.3,18.0,195.0,3250.0,FEMALE
Torgersen,Adelie,NaN,NaN,NaN,NaN,NaN
Torgersen,Adelie,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...
Biscoe,Gentoo,NaN,NaN,NaN,NaN,NaN
Biscoe,Gentoo,46.8,14.3,215.0,4850.0,FEMALE
Biscoe,Gentoo,50.4,15.7,222.0,5750.0,MALE
Biscoe,Gentoo,45.2,14.8,212.0,5200.0,FEMALE
Biscoe,Gentoo,49.9,16.1,213.0,5400.0,MALE

In [ ]:
df.reset_index(inplace=True)

In [ ]:
# The number of values for each key must be the same, otherwise pandas will raise a ValueError when creating the DataFrame.
# The dictionary 'd' below is now defined with lists of equal length to prevent this error.
d ={
    'key1':[6,3,8,5],
    'key3':[5,6,8,9],
    'key5':[4,5,6,8]
}

In [ ]:
pd.DataFrame(d)

   key1  key3  key5
0     6     5     4
1     3     6     5
2     8     8     6
3     5     9     8

In [ ]:
#Remove rows or columns that contain missing values (represented as NaN or None)
df.dropna(inplace=True)

In [ ]:
df

,island,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Torgersen,Adelie,39.1,18.7,181.0,3750.0,MALE
1,Torgersen,Adelie,39.5,17.4,186.0,3800.0,FEMALE
2,Torgersen,Adelie,40.3,18.0,195.0,3250.0,FEMALE
4,Torgersen,Adelie,36.7,19.3,193.0,3450.0,FEMALE
5,Torgersen,Adelie,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Biscoe,Gentoo,47.2,13.7,214.0,4925.0,FEMALE
340,Biscoe,Gentoo,46.8,14.3,215.0,4850.0,FEMALE
341,Biscoe,Gentoo,50.4,15.7,222.0,5750.0,MALE
342,Biscoe,Gentoo,45.2,14.8,212.0,5200.0,FEMALE
343,Biscoe,Gentoo,49.9,16.1,213.0,5400.0,MALE

In [ ]:
#Rremove columns that contain missing values, also known as NaN (Not a Number)
df.dropna(axis=1)

,island,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Torgersen,Adelie,39.1,18.7,181.0,3750.0,MALE
1,Torgersen,Adelie,39.5,17.4,186.0,3800.0,FEMALE
2,Torgersen,Adelie,40.3,18.0,195.0,3250.0,FEMALE
4,Torgersen,Adelie,36.7,19.3,193.0,3450.0,FEMALE
5,Torgersen,Adelie,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Biscoe,Gentoo,47.2,13.7,214.0,4925.0,FEMALE
340,Biscoe,Gentoo,46.8,14.3,215.0,4850.0,FEMALE
341,Biscoe,Gentoo,50.4,15.7,222.0,5750.0,MALE
342,Biscoe,Gentoo,45.2,14.8,212.0,5200.0,FEMALE
343,Biscoe,Gentoo,49.9,16.1,213.0,5400.0,MALE

In [ ]:
df1 = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/titanic.csv')

In [ ]:
df1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
# This code removes columns from `df1` that contain any missing values (NaN).
# The `axis=1` argument specifies that columns should be dropped, not rows.
# `inplace=True` ensures the modification is applied directly to `df1`.
df1.dropna(axis=1)

,survived,pclass,sex,sibsp,parch,fare,class,who,adult_male,alive,alone
0,0,3,male,1,0,7.2500,Third,man,True,no,False
1,1,1,female,1,0,71.2833,First,woman,False,yes,False
2,1,3,female,0,0,7.9250,Third,woman,False,yes,True
3,1,1,female,1,0,53.1000,First,woman,False,yes,False
4,0,3,male,0,0,8.0500,Third,man,True,no,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,0,0,13.0000,Second,man,True,no,True
887,1,1,female,0,0,30.0000,First,woman,False,yes,True
888,0,3,female,1,2,23.4500,Third,woman,False,no,False
889,1,1,male,0,0,30.0000,First,man,True,yes,True
890,0,3,male,0,0,7.7500,Third,man,True,no,True

In [ ]:
df1.fillna('ABC')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,ABC,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,ABC,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,ABC,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,ABC,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,ABC,1,2,23.4500,S,Third,woman,False,ABC,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,ABC,Queenstown,no,True

In [ ]:
# Grouping
g = df1.groupby('survived')

In [ ]:
g

In [ ]:
g.sum()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
survived,,,,,,,,,,,,,,
0,1390,malemalemalemalemalemalemalefemalemalefemalema...,12985.50,304,181,12142.7199,SSQSSSSSQSSSCSSCSCSSSSSCSQCSSSCCSCSSCSSSSSCSSS...,ThirdThirdThirdFirstThirdThirdThirdThirdThirdT...,manmanmanmanchildmanmanchildchildwomanmanchild...,449,ECBCFEADCBDCBFBACAGCGCEBCADCCCCCCECCEEABCCCDCB...,SouthamptonSouthamptonQueenstownSouthamptonSou...,nonononononononononononononononononononononono...,374
1,667,femalefemalefemalefemalefemalefemalefemalefema...,8219.67,162,159,16551.2294,CSSSCSSSSCSQSSQCQCCCQQCSSSSCSSSSSSQSSSCSSSQSCS...,FirstThirdFirstThirdSecondThirdFirstSecondSeco...,womanwomanwomanwomanchildchildwomanwomanmanwom...,88,CCGCDABDCBFCDEFDCEFFBBADDCCDBCCDBCBECCECBCECDB...,CherbourgSouthamptonSouthamptonSouthamptonCher...,yesyesyesyesyesyesyesyesyesyesyesyesyesyesyesy...,163

In [ ]:
# Previously, g.sum() produced concatenated strings because it summed all columns.
# Using `numeric_only=True` resolves this by summing only the numerical columns,
# avoiding the concatenation of non-numeric data.
g.sum(numeric_only=True)

          pclass       age  sibsp  parch        fare  adult_male  alone
survived
0           1390  12985.50    304    181  12142.7199         449    374
1            667   8219.67    162    159  16551.2294          88    163

In [ ]:
g.mean(numeric_only=True)

,pclass,age,sibsp,parch,fare,adult_male,alone
survived,,,,,,,
0,2.531876,30.626179,0.553734,0.329690,22.117887,0.817851,0.681239
1,1.950292,28.343690,0.473684,0.464912,48.395408,0.257310,0.476608

In [ ]:
g1 = df1.groupby(['survived','sex'])

In [ ]:
g1.sum(numeric_only=True)

                 pclass       age  sibsp  parch        fare  adult_male  alone
survived sex
0        female     231   1603.00     98     84   1864.9752           0     27
         male      1159  11382.50    206     97  10277.7447         449    347
1        female     447   5683.00    120    120  12101.6876           0     99
         male       220   2536.67     42     39   4449.5418          88     64

In [ ]:
g2 = df1.groupby('pclass')

In [ ]:
g2.sum(numeric_only=True)

        survived      age  sibsp  parch        fare  adult_male  alone
pclass
1            136  7111.42     90     77  18177.4125         119    109
2             87  5168.83     74     70   3801.8417          99    104
3            119  8924.92    302    193   6714.6951         319    324

In [ ]:
g2.max(numeric_only=True)

        survived   age  sibsp  parch      fare  adult_male  alone
pclass
1              1  80.0      3      4  512.3292        True   True
2              1  70.0      3      3   73.5000        True   True
3              1  74.0      8      6   69.5500        True   True

In [ ]:
# This code first calculates the maximum value for each numeric column
# within each passenger class (grouped by 'pclass' in `g2`).
# The `numeric_only=True` argument ensures only numerical columns are considered.
# Finally, `.transpose()` is applied to swap the rows and columns,
# making it easier to compare the maximum values across different passenger classes (pclass 1, 2, 3).
g2.max(numeric_only=True).transpose()

pclass             1     2      3
survived           1     1      1
age             80.0  70.0   74.0
sibsp              3     3      8
parch              4     3      6
fare        512.3292  73.5  69.55
adult_male      True  True   True
alone           True  True   True

In [ ]:
df3 = df1[['survived','pclass','sex']][0:5]

In [ ]:
df4 = df1[['survived','pclass','sex']][5:10]

In [ ]:
pd.concat([df3,df4])

   survived  pclass     sex
0         0       3    male
1         1       1  female
2         1       3  female
3         1       1  female
4         0       3    male
5         0       3    male
6         0       1    male
7         0       3    male
8         1       3  female
9         1       2  female

In [ ]:
# This code concatenates `df3` and `df4` column-wise (axis=1).
# Because `df3` and `df4` have different index ranges (0-4 and 5-9 respectively),
# `pandas` aligns them by index. Where an index exists in one DataFrame but not the other,
# `NaN` (Not a Number) values are introduced to fill the missing entries.
pd.concat([df3,df4],axis=1)

   survived  pclass     sex  survived  pclass     sex
0       0.0     3.0    male       NaN     NaN     NaN
1       1.0     1.0  female       NaN     NaN     NaN
2       1.0     3.0  female       NaN     NaN     NaN
3       1.0     1.0  female       NaN     NaN     NaN
4       0.0     3.0    male       NaN     NaN     NaN
5       NaN     NaN     NaN       0.0     3.0    male
6       NaN     NaN     NaN       0.0     1.0    male
7       NaN     NaN     NaN       0.0     3.0    male
8       NaN     NaN     NaN       1.0     3.0  female
9       NaN     NaN     NaN       1.0     2.0  female

In [ ]:
# Count the number of people who survived (1) and did not survive (0)
df1.groupby('survived').size()

survived
0    549
1    342
dtype: int64

In [ ]:
# This code groups the DataFrame `df1` first by 'pclass' (passenger class)
# and then by 'sex'. After grouping, `size()` is used to count the number
# of rows in each group, effectively showing the distribution of males and
# females within each passenger class.
df1.groupby(['pclass', 'sex']).size()

pclass  sex
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
dtype: int64

In [ ]:
# Group by 'pclass' and 'survived' to count the number of people who survived
# (1) or did not survive (0) within each passenger class.
df1.groupby(['pclass', 'survived']).size()

pclass  survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
dtype: int64

In [ ]:
datat1 = pd.DataFrame({
        'key1':[1,2,3,4,5],
        'key5':[6,7,8,9,10],
        'key6':[11,12,13,14,15]
    })

In [ ]:
data2 = pd.DataFrame({
        'key1':[3,5,6,7,10],
        'key2':[9,10,11,12,13],
        'key3':[31,32,14,15,35]
    })

In [ ]:
pd.merge(datat1, data2)

   key1  key5  key6  key2  key3
0     3     8    13     9    31
1     5    10    15    10    32

In [ ]:
pd.merge(datat1, data2,how='left')

   key1  key5  key6  key2  key3
0     1     6    11   NaN   NaN
1     2     7    12   NaN   NaN
2     3     8    13   9.0  31.0
3     4     9    14   NaN   NaN
4     5    10    15  10.0  32.0

In [ ]:
pd.merge(datat1, data2,how='right')

   key1  key5  key6  key2  key3
0     3   8.0  13.0     9    31
1     5  10.0  15.0    10    32
2     6   NaN   NaN    11    14
3     7   NaN   NaN    12    15
4    10   NaN   NaN    13    35

In [ ]:
pd.merge(datat1, data2,how='cross')

    key1_x  key5  key6  key1_y  key2  key3
0        1     6    11       3     9    31
1        1     6    11       5    10    32
2        1     6    11       6    11    14
3        1     6    11       7    12    15
4        1     6    11      10    13    35
5        2     7    12       3     9    31
6        2     7    12       5    10    32
7        2     7    12       6    11    14
8        2     7    12       7    12    15
9        2     7    12      10    13    35
10       3     8    13       3     9    31
11       3     8    13       5    10    32
12       3     8    13       6    11    14
13       3     8    13       7    12    15
14       3     8    13      10    13    35
15       4     9    14       3     9    31
16       4     9    14       5    10    32
17       4     9    14       6    11    14
18       4     9    14       7    12    15
19       4     9    14      10    13    35
20       5    10    15       3     9    31
21       5    10    15       5    10    32
22       5    10    15       6    11    14
23       5    10    15       7    12    15
24       5    10    15      10    13    35

In [ ]:
data1 = pd.DataFrame({
        'key1':[1,2,3,4,5],
        'key2':[6,7,8,9,10],
        'key3':[11,12,13,14,15]},
        index = ['a','b','c','d','e']
    )

In [ ]:
data1

   key1  key2  key3
a     1     6    11
b     2     7    12
c     3     8    13
d     4     9    14
e     5    10    15

In [ ]:
data2 = pd.DataFrame({
        'key11':[1,2,3,4,5],
        'key12':[6,7,8,9,10],
        'key13':[11,12,13,14,15]},
        index = ['a','b','h','i','j']
    )

In [ ]:
data2

   key11  key12  key13
a      1      6     11
b      2      7     12
h      3      8     13
i      4      9     14
j      5     10     15

In [ ]:
data1.join(data2)

   key1  key2  key3  key11  key12  key13
a     1     6    11    1.0    6.0   11.0
b     2     7    12    2.0    7.0   12.0
c     3     8    13    NaN    NaN    NaN
d     4     9    14    NaN    NaN    NaN
e     5    10    15    NaN    NaN    NaN

In [ ]:
data1.join(data2,how='inner')

   key1  key2  key3  key11  key12  key13
a     1     6    11      1      6     11
b     2     7    12      2      7     12

In [ ]:
data1.join(data2,how='right')

   key1  key2  key3  key11  key12  key13
a   1.0   6.0  11.0      1      6     11
b   2.0   7.0  12.0      2      7     12
h   NaN   NaN   NaN      3      8     13
i   NaN   NaN   NaN      4      9     14
j   NaN   NaN   NaN      5     10     15

In [ ]:
data1.join(data2,how='outer')

   key1  key2  key3  key11  key12  key13
a   1.0   6.0  11.0    1.0    6.0   11.0
b   2.0   7.0  12.0    2.0    7.0   12.0
c   3.0   8.0  13.0    NaN    NaN    NaN
d   4.0   9.0  14.0    NaN    NaN    NaN
e   5.0  10.0  15.0    NaN    NaN    NaN
h   NaN   NaN   NaN    3.0    8.0   13.0
i   NaN   NaN   NaN    4.0    9.0   14.0
j   NaN   NaN   NaN    5.0   10.0   15.0