<a href="https://colab.research.google.com/github/rijul27/Exploring-Pandas/blob/pandas-basics/Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd

**[Reading a CSV file ](https://)**

In [3]:
df = pd.read_csv("annual.csv")

In [ ]:
print(df)

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2024                     Level 1                99999
1      2024                     Level 1                99999
2      2024                     Level 1                99999
3      2024                     Level 1                99999
4      2024                     Level 1                99999
...     ...                         ...                  ...
55615  2013                     Level 3                 ZZ11
55616  2013                     Level 3                 ZZ11
55617  2013                     Level 3                 ZZ11
55618  2013                     Level 3                 ZZ11
55619  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
55615  Food product manufacturing          Percentage           H37
55616  Food product manufacturing          Percentage           H38
55617  Food product manufacturing          Percentage           H39
55618  Food product manufacturing          Percentage           H40
55619  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
55615                                      Quick ratio       Financial ratios
55616              Margin on sales of goods for resale       Financial ratios
55617                                 Return on equity       Financial ratios
55618                           Return on total assets       Financial ratios
55619                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      979594  ANZSIC06 divisions A-S (excluding classes K633...
1      838626  ANZSIC06 divisions A-S (excluding classes K633...
2      112188  ANZSIC06 divisions A-S (excluding classes K633...
3       28781  ANZSIC06 divisions A-S (excluding classes K633...
4      856960  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
55615      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55616      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55617      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55618       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
55619      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[55620 rows x 10 columns]

In [4]:
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [5]:
#The code df.head() is used to display the first 5 rows of the DataFrame named df.
#This is a common method in the pandas library for quickly inspecting the beginning of a dataset.
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...

In [ ]:
df.head(10)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2024,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,979594,ANZSIC06 divisions A-S (excluding classes K633...
1,2024,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,838626,ANZSIC06 divisions A-S (excluding classes K633...
2,2024,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,112188,ANZSIC06 divisions A-S (excluding classes K633...
3,2024,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,28781,ANZSIC06 divisions A-S (excluding classes K633...
4,2024,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,856960,ANZSIC06 divisions A-S (excluding classes K633...
5,2024,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,71493,ANZSIC06 divisions A-S (excluding classes K633...
6,2024,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,8540,ANZSIC06 divisions A-S (excluding classes K633...
7,2024,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,32896,ANZSIC06 divisions A-S (excluding classes K633...
8,2024,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,157616,ANZSIC06 divisions A-S (excluding classes K633...
9,2024,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,323,ANZSIC06 divisions A-S (excluding classes K633...

In [6]:
#The code df.head(0) displays only the column headers of the DataFrame df and no rows.
df.head(0)

Empty DataFrame
Columns: [Year, Industry_aggregation_NZSIOC, Industry_code_NZSIOC, Industry_name_NZSIOC, Units, Variable_code, Variable_name, Variable_category, Value, Industry_code_ANZSIC06]
Index: []

In [7]:
#The code df.tail() is used to display the last 5 rows of the DataFrame named df.
df.tail()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
55615,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55616,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55617,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55618,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
55619,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
#df is a pandas DataFrame, so this code will output pandas.core.frame.DataFrame, indicating that df is an instance of the DataFrame class from the pandas library.
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.columns

Index(['Year', 'Industry_aggregation_NZSIOC', 'Industry_code_NZSIOC',
       'Industry_name_NZSIOC', 'Units', 'Variable_code', 'Variable_name',
       'Variable_category', 'Value', 'Industry_code_ANZSIC06'],
      dtype='object')

In [8]:
# The code list(df.columns) retrieves all the column names from your DataFrame
# df and converts them into a standard Python list.
list(df.columns)

['Year',
 'Industry_aggregation_NZSIOC',
 'Industry_code_NZSIOC',
 'Industry_name_NZSIOC',
 'Units',
 'Variable_code',
 'Variable_name',
 'Variable_category',
 'Value',
 'Industry_code_ANZSIC06']

In [ ]:
df['Units']

0        Dollars (millions)
1        Dollars (millions)
2        Dollars (millions)
3        Dollars (millions)
4        Dollars (millions)
                ...
55615            Percentage
55616            Percentage
55617            Percentage
55618            Percentage
55619            Percentage
Name: Units, Length: 55620, dtype: object

In [ ]:
# type(df['Units']) is used to identify the data type of the 'Units' column within your DataFrame df. When you select a single column from a pandas DataFrame like this, the output is a pandas Series. Therefore, this code will return pandas.core.series.Series, indicating that 'Units'
type(df['Units'])

pandas.core.series.Series

In [ ]:
df['Value','variables']

# df['Value','variables'] is attempting to select multiple columns from your DataFrame df. However, the way you've written it, pandas interprets ('Value', 'variables') as a single column name, which doesn't exist in your DataFrame. This results in a KeyError, as seen in the output. To select multiple columns, you need to pass a list of column names within the square brackets, like df[['Value', 'Variable_name']].

KeyError: ('Value', 'variables')

   Feature_1  Feature_2
0   0.544837   0.334246
1   0.561907   0.425006
2   0.785737   0.558289