<a href="https://colab.research.google.com/github/rijul27/Exploring-Pandas/blob/main/pandasMethods2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data ={
    'a' : [5,8,9,6],
    'b' : [1,2,4,8],
    'c' : ['ml','dl','aws','genAi']
}

In [ ]:
#convert dic into df
df = pd.DataFrame(data)

In [ ]:
df

   a  b      c
0  5  1     ml
1  8  2     dl
2  9  4    aws
3  6  8  genAi

In [ ]:
df.set_index('a',inplace=True)

In [ ]:
df

   b      c
a
5  1     ml
8  2     dl
9  4    aws
6  8  genAi

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

   a  b      c
0  5  1     ml
1  8  2     dl
2  9  4    aws
3  6  8  genAi

In [ ]:
df['a']

0    5
1    8
2    9
3    6
Name: a, dtype: int64

In [ ]:
list(df['a'])

[5, 8, 9, 6]

In [ ]:
for i in df['a']:
    print(i)

5
8
9
6

In [ ]:
[i for i in df['a']]

[5, 8, 9, 6]

In [ ]:
# Apply function
def test(x):
  return x.sum()
df.apply(test,axis=0)

a              28
b              15
c    mldlawsgenAi
dtype: object

In [ ]:
df1 = df[['a','b']]

In [ ]:
df1

   a  b
0  5  1
1  8  2
2  9  4
3  6  8

In [ ]:
df1.applymap(lambda x : x**2)

/tmp/ipykernel_3374/1241945342.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1.applymap(lambda x : x**2)

    a   b
0  25   1
1  64   4
2  81  16
3  36  64

In [ ]:
df

   a  b      c
0  5  1     ml
1  8  2     dl
2  9  4    aws
3  6  8  genAi

In [ ]:
df.sort_values('c')

   a  b      c
2  9  4    aws
1  8  2     dl
3  6  8  genAi
0  5  1     ml

In [ ]:
df.sort_index()

   a  b      c
0  5  1     ml
1  8  2     dl
2  9  4    aws
3  6  8  genAi

In [ ]:
df.sort_index(ascending=False)

   a  b      c
3  6  8  genAi
2  9  4    aws
1  8  2     dl
0  5  1     ml

In [ ]:
#Set_Option
pd.DataFrame({'Desc':["Data science is a multidisciplinary field that combines mathematics, statistics, computer programming, and domain expertise to extract meaningful insights from raw data"]})

                                                                                                                                                                       Desc
0  Data science is a multidisciplinary field that combines mathematics, statistics, computer programming, and domain expertise to extract meaningful insights from raw data

In [ ]:
pd.set_option('display.max_colwidth',500)
pd.DataFrame({'Desc':["Data science is a multidisciplinary field that combines mathematics, statistics, computer programming, and domain expertise to extract meaningful insights from raw data"]})

                                                                                                                                                                       Desc
0  Data science is a multidisciplinary field that combines mathematics, statistics, computer programming, and domain expertise to extract meaningful insights from raw data

In [ ]:
pd.set_option('display.max_colwidth',500)
df2 = pd.DataFrame({'Desc':["Data science is a multidisciplinary field that combines mathematics, statistics, computer programming, and domain expertise to extract meaningful insights from raw data","I am DataScience","Learn me"]})

In [ ]:
df2

                                                                                                                                                                       Desc
0  Data science is a multidisciplinary field that combines mathematics, statistics, computer programming, and domain expertise to extract meaningful insights from raw data
1                                                                                                                                                          I am DataScience
2                                                                                                                                                                  Learn me

In [ ]:
df2['Desc'].apply(len)

0    168
1     16
2      8
Name: Desc, dtype: int64

In [ ]:
df2['length'] = df2['Desc'].apply(len)

In [ ]:
df2

,Desc,length
0,"Data science is a multidisciplinary field that combines mathematics, statistics, computer programming, and domain expertise to extract meaningful insights from raw data",168
1,I am DataScience,16
2,Learn me,8

In [ ]:
s = "Hello DataScience and GenAi"
s.split()

['Hello', 'DataScience', 'and', 'GenAi']

In [ ]:
len(s.split())

4

In [ ]:
df2['Desc'].apply(lambda x : x.split())

0    [Data, science, is, a, multidisciplinary, field, that, combines, mathematics,, statistics,, computer, programming,, and, domain, expertise, to, extract, meaningful, insights, from, raw, data]
1                                                                                                                                                                               [I, am, DataScience]
2                                                                                                                                                                                        [Learn, me]
Name: Desc, dtype: object

In [ ]:
df2['Desc'].apply(lambda x : len(x.split()))

0    22
1     3
2     2
Name: Desc, dtype: int64

In [ ]:
df2['word_count'] = df2['Desc'].apply(lambda x : len(x.split()))

In [ ]:
df2

,Desc,length,word_count
0,"Data science is a multidisciplinary field that combines mathematics, statistics, computer programming, and domain expertise to extract meaningful insights from raw data",168,22
1,I am DataScience,16,3
2,Learn me,8,2

In [ ]:
df

   a  b      c
0  5  1     ml
1  8  2     dl
2  9  4    aws
3  6  8  genAi

In [ ]:
df['a'][1]

np.int64(8)

In [ ]:
df['a'].sum()

np.int64(28)

In [ ]:
df['a'].mean()

np.float64(7.0)

In [ ]:
df['b'].median()

3.0

In [ ]:
df['b'].mode()

0    1
1    2
2    4
3    8
Name: b, dtype: int64

In [ ]:
df['a'].std()

1.8257418583505538

In [ ]:
df['a'].max()

9

In [ ]:
df['b'].min()

1

In [ ]:
df['b'].var()

9.583333333333334

In [ ]:
#Pandas window function

In [ ]:
df3 = pd.DataFrame({'a':[1,2,3,4,5,6,7,8,9,10]})

In [ ]:
df3

    a
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [ ]:
# This code is creating a 'rolling' object on the 'a' column of
# your DataFrame df. This object allows you to perform window-based
# calculations, such as rolling averages or sums, over your data.
# In this specific case, window=1 means that each 'window' considered
# for calculation will consist of only one element. You would typically
# follow this with an aggregation function, like .mean() or .sum(), to
# get a result. With a window of 1, the result of such an aggregation
# would just be the original series itself.

df3['a'].rolling(window=1)

Rolling [window=1,center=False,axis=0,method=single]

In [ ]:
df3['a'].rolling(window=1).mean()

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     7.0
7     8.0
8     9.0
9    10.0
Name: a, dtype: float64

In [ ]:
df3['a'].rolling(window=2).mean()

0    NaN
1    1.5
2    2.5
3    3.5
4    4.5
5    5.5
6    6.5
7    7.5
8    8.5
9    9.5
Name: a, dtype: float64

In [ ]:
df3['a'].rolling(window=3).mean()

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
Name: a, dtype: float64

In [ ]:
df3['a'].rolling(window=3).sum()

0     NaN
1     NaN
2     6.0
3     9.0
4    12.0
5    15.0
6    18.0
7    21.0
8    24.0
9    27.0
Name: a, dtype: float64

In [ ]:
# Cummulative sum
df3['a'].cumsum()

0     1
1     3
2     6
3    10
4    15
5    21
6    28
7    36
8    45
9    55
Name: a, dtype: int64

In [ ]:
# pandas Date Functionality

In [ ]:
date = pd.date_range(start='2024-02-22',end='2024-02-28')

In [ ]:
date

DatetimeIndex(['2024-02-22', '2024-02-23', '2024-02-24', '2024-02-25',
               '2024-02-26', '2024-02-27', '2024-02-28'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
# This code creates a Pandas DataFrame where the 'date' column contains a
# range of dates generated previously.
df_date = pd.DataFrame({'date':date})

In [ ]:
df_date

        date
0 2024-02-22
1 2024-02-23
2 2024-02-24
3 2024-02-25
4 2024-02-26
5 2024-02-27
6 2024-02-28

In [ ]:
df5 = pd.DataFrame({'date' :['2024-02-26','2024-02-27']})

In [ ]:
df5

         date
0  2024-02-26
1  2024-02-27

In [ ]:
df5.dtypes

date    object
dtype: object

In [ ]:
df5['updated_date _to_datetime']=pd.to_datetime(df5['date'])

In [ ]:
df5

         date updated_date _to_datetime
0  2024-02-26                2024-02-26
1  2024-02-27                2024-02-27

In [ ]:
df5['year'] = df5['updated_date _to_datetime'].dt.year

In [ ]:
df5

         date updated_date _to_datetime  year
0  2024-02-26                2024-02-26  2024
1  2024-02-27                2024-02-27  2024

In [ ]:
df5['day'] = df5['updated_date _to_datetime'].dt.day

In [ ]:
df5

         date updated_date _to_datetime  year  day
0  2024-02-26                2024-02-26  2024   26
1  2024-02-27                2024-02-27  2024   27

In [ ]:
df5['month'] = df5['updated_date _to_datetime'].dt.month

In [ ]:
df5

         date updated_date _to_datetime  year  day  month
0  2024-02-26                2024-02-26  2024   26      2
1  2024-02-27                2024-02-27  2024   27      2

In [ ]:
#pandas time delta

In [ ]:
pd.Timedelta(days=1,hours=7,minutes=45)

Timedelta('1 days 07:45:00')

In [ ]:
dt = pd.to_datetime('2026-06-13')

In [ ]:
td = pd.Timedelta(days=1)

In [ ]:
td

Timedelta('1 days 00:00:00')

In [ ]:
dt + td

Timestamp('2026-06-14 00:00:00')

In [ ]:
#categorical data

In [ ]:
data = ['ml','dl','aws','ml','python','cloud']

In [ ]:
c = pd.Categorical(data)

In [ ]:
c.value_counts()

aws       1
cloud     1
dl        1
ml        2
python    1
Name: count, dtype: int64

In [ ]:
# pandas -