<a href="https://colab.research.google.com/github/rijul27/Exploring-Pandas/blob/main/Series_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = [1,2,3,4]

In [ ]:
pd.Series(data)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
type(data)

list

In [ ]:
type(pd.Series(data))

pandas.core.series.Series

In [ ]:
# Accessing elements
series = pd.Series(data)
series[0]

np.int64(1)

In [ ]:
series[1:4]

1    2
2    3
3    4
dtype: int64

In [ ]:
series1 = pd.Series([1,2,3])
series2 = pd.Series([4,5,6])

result = series1 + series2
print(result)

0    5
1    7
2    9
dtype: int64

In [ ]:
type(result)

pandas.core.series.Series

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/roberthryniewicz/datasets/refs/heads/master/airline-dataset/flights/flights.csv')

In [ ]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0

In [ ]:
df.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [ ]:
s = df['DepTime'][0:8]

In [ ]:
s

0    2003.0
1     754.0
2     628.0
3     926.0
4    1829.0
5    1940.0
6    1937.0
7    1039.0
Name: DepTime, dtype: float64

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
l = ['a','b','c','d','e','f','g','h']

In [ ]:
s1 = pd.Series(list(s),index=l)
print(s1)
# creates a new pandas Series. It takes the values from the existing Series s
# by converting them into a Python list using list(s). Then, it uses the list l
# (which contains ['a','b','c','d','e','f','g','h']) to assign custom labels as
# the index for this new Series. So, instead of the default numerical index,
# you get a Series with 'a' through 'h' as its index.

a    2003.0
b     754.0
c     628.0
d     926.0
e    1829.0
f    1940.0
g    1937.0
h    1039.0
dtype: float64

In [ ]:
pd.Series(s,index=l)

# When you use pd.Series(s, index=l), pandas tries to align the existing Series
# s with the new index l. Since s has a default numerical index (0, 1, 2, ...)
# and l has a different, custom string index ('a', 'b', 'c', ...), there are no
# common labels between the two indices. Because pandas attempts to match labels
# during this operation, and finding no matches, it fills the new Series with
# NaN (Not a Number) values. This might not always raise an explicit error, but
# it often results in a Series full of NaNs, which is typically not the desired
# outcome and can be perceived as an error or incorrect behavior.

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
Name: DepTime, dtype: float64

In [ ]:
s1[0]

/tmp/ipykernel_5311/643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.float64(2003.0)

In [ ]:
s1['a']

np.float64(2003.0)

In [ ]:
s[0]

np.float64(2003.0)

In [ ]:
s2 = pd.concat([s1, s])

In [ ]:
s2

a    2003.0
b     754.0
c     628.0
d     926.0
e    1829.0
f    1940.0
g    1937.0
h    1039.0
0    2003.0
1     754.0
2     628.0
3     926.0
4    1829.0
5    1940.0
6    1937.0
7    1039.0
dtype: float64

In [ ]:
s3 = pd.Series([100,200,300,400,500], index = [2,4,5,6,1])

In [ ]:
s3

2    100
4    200
5    300
6    400
1    500
dtype: int64

In [ ]:
s4 = pd.Series([4,5,6,7,8,9], index=[9,10,4,5,13,14])

In [ ]:
s4

9     4
10    5
4     6
5     7
13    8
14    9
dtype: int64

In [ ]:
s5 =  pd.concat([s3, s4])

In [ ]:
s5

2     100
4     200
5     300
6     400
1     500
9       4
10      5
4       6
5       7
13      8
14      9
dtype: int64

In [ ]:
# s5[4] is accessing elements from the pandas Series s5 using its index label.
# In this particular Series, the index label 4 appears more than once due to the
# concatenation of s3 and s4. When you index a Series with a label that has
# duplicates, pandas returns all entries corresponding to that label as a new
# Series. That's why the output shows both 200 (from s3) and 6 (from s4), both
# with the index 4.

s5[4]

4    200
4      6
dtype: int64

In [ ]:
s3 + s4

1       NaN
2       NaN
4     206.0
5     307.0
6       NaN
9       NaN
10      NaN
13      NaN
14      NaN
dtype: float64

In [ ]:
s3 * s4

1        NaN
2        NaN
4     1200.0
5     2100.0
6        NaN
9        NaN
10       NaN
13       NaN
14       NaN
dtype: float64